FROM maven:3.8-jdk-11
MAINTAINER ibm.com

COPY pom.xml /home/app
COPY src /home/app/src

WORKDIR /home/app

RUN mvn -f pom.xml clean install

EXPOSE 9595

ENTRYPOINT ["java", "-jar", "target/cron-0.0.1-SNAPSHOT.jar"]